version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/ssl.conf.template:/etc/nginx/conf.d/ssl.conf.template
      - ./certs:/etc/nginx/certs
    environment:
      - DOMAIN=${DOMAIN}
    command: >
      sh -c "envsubst '$$DOMAIN' < /etc/nginx/conf.d/ssl.conf.template > /etc/nginx/conf.d/ssl.conf
      && nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge