version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/certbot/ssl:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/nginx/certbot/ssl:/etc/letsencrypt
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge